name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # هذه الخطوة ستقوم بصناعة ملف gradlew تلقائياً في سيرفر GitHub
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Build Plugins
        run: gradle make

      - name: Deploy to Builds
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: builds
