name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true # مهم جداً لهذا النوع من المستودعات

      - name: Build Plugins
        # هذا هو الرابط الصحيح الذي يعمل مع مستودع الـ Archive
        uses: recloudstream/cloudstream-archive-action@master
        with:
          # إذا كنت تستخدم Java/Kotlin اتركها false، إذا كنت تستخدم JS اجعلها true
          is-js-repo: false 
          # لتوليد ملف الـ JSON الخاص بالمستودع تلقائياً
          make-repo: true
